power=read.table("household_power_consumption.txt",header=T,na.strings = "?",sep=";",stringsAsFactors = FALSE)
str(power)
power$DateTime=strptime(paste(power$Date,power$Time,sep=" "),format ="%d/%m/%Y %H:%M:%S")
str(power)

power=subset(power,(as.Date(power$DateTime))>="2007-02-01" & (as.Date(power$DateTime))<="2007-02-02")
str(power)
power$Weekday=wday(power$Date,label = T)
str(power)
windows()
png(file="plot4.png")
par(mfrow=c(2,2))
plot( power$DateTime,power$Global_active_power,type="l",ylab = "Global Active Power",xlab = "")
plot(power$DateTime,power$Voltage,type = "l",xlab = "datetime",ylab = "Voltage")
plot( power$DateTime,power$Sub_metering_1,type="l",ylab = "Energy sub metering",xlab = "",col="black")
lines( power$DateTime,power$Sub_metering_2,type="l",ylab = "Global Active Power (kilowatts)",xlab = "",col="red")
lines( power$DateTime,power$Sub_metering_3,type="l",ylab = "Global Active Power (kilowatts)",xlab = "",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),col = c("black","red","blue"))
plot(power$DateTime,power$Global_reactive_power,type="l",xlab = "datetime",ylab="Global_reactive_power")
dev.off()
